apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "url-utilities.fullname" . }}
  labels:
    {{- include "url-utilities.labels" . | nindent 4 }}
data:
  APP_URL: {{ .Values.config.APP_URL | quote }}
